name: Check formatting

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Check Ruff linting
        uses: chartboost/ruff-action@v1
        with:
          args: 'check'

      - name: Check Ruff formatting
        if: success() || failure()
        uses: chartboost/ruff-action@v1
        with:
          args: 'format --check'

      - name: Check Prettier formatting
        if: success() || failure()
        uses: creyD/prettier_action@v4.3
        with:
          prettier_version: '2.8.8'
          dry: true
          prettier_options: '--check .'

  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4

      - name: Run check-translations.js
        run: node check-translations.js >> $GITHUB_STEP_SUMMARY
        working-directory: ./.github/workflow_utils
