name: Check formatting

on:
  push:
  pull_request:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - name: Check Ruff linting
        uses: astral-sh/ruff-action@v3
        with:
          args: 'check'

      - name: Check Ruff formatting
        if: success() || failure()
        uses: astral-sh/ruff-action@v3
        with:
          args: 'format --check'

      - name: Check Prettier formatting
        if: success() || failure()
        uses: creyD/prettier_action@v4.5 # This can be bumped when https://github.com/creyD/prettier_action/issues/154 is solved
        with:
          prettier_version: '2.8.8'
          dry: true
          prettier_options: '--check .'

  translations:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6

      - uses: actions/setup-node@v6

      - name: Run check-translations.js
        run: node check-translations.js >> $GITHUB_STEP_SUMMARY
        working-directory: ./.github/workflow_utils
