name: 'Stale Issue Handler'
on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/stale@main
        with:
          stale-issue-message: 'This issue is stale because it has been open for 60 days with no activity. Remove stale label or comment on this issue or it will be closed in 5 days.'
          close-issue-message: 'Closing issue due to no activity in more than 60 days.'
          days-before-stale: 30
          days-before-close: 5
          exempt-issue-labels: 'blocked,keep'
